<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Terminos.aspx.cs" Inherits="ManagCond.Terminos" %>


<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>ManagCond</title>
    <link rel="stylesheet" href="../assets/css/factura.css" media="all"/>
</head>
<body>
    <div class="legal w-richtext">
        <h2>“CONTRATO DE PRESTACION DE SERVICIOS DE SOFTWARE PARA LA ADMINISTRACION DE<br>
            EDIFICIOS Y CONDOMINIOS”<br>
        </h2>
        <p>‍<br>
            <br>
            En Santiago de Chile, a ___________________________________________, entre <strong>ManagCond SpA</strong>, Rut: 76.474.965-0, en adelante <strong>LA EMPRESA</strong> representada por Antti Mihael Kulppi Quezada, Rut: 18.156.895-k, chileno, ambos con domicilio en Apoquindo 2930, piso 2, Las Condes, por una parte; y _________________________________________, Rut: ________________________, representada por</p>
        <p>_____________________________________________, Run:__________________ </p>
        <p>Nacionalidad: ____________________, Dirección _______________________________________________, en adelante <strong>EL CLIENTE</strong>, todos mayores de edad, exponen que han acordado celebrar el siguiente contrato de prestación de servicios de software.</p>
        <p><strong>PRIMERO. Descripción del servicio:</strong> El siguiente contrato tiene por objeto la prestación de servicios informáticos que suministra LA EMPRESA, consistente en el arriendo de una plataforma tecnológica online y las asesorías en el uso de ella.</p>
        <p>La plataforma, en adelante e indistintamente, “ManagCond”, “software” o “sistema”, tiene como propósito apoyar la administración de edificios y condominios bajo régimen de copropiedad.</p>
        <p><strong>SEGUNDO. Obligaciones de las partes</strong></p>
        <p>a. Implementación del sistema: ManagCond es una plataforma online. Para su acceso el CLIENTE debe considerar un computador con conexión a internet y un navegador web.</p>
        <p>b. Entrega de información: Con la suscripción del siguiente contrato, el CLIENTE se obliga a entregar la debida información, correspondiente a nómina completa de datos personales de los copropietarios (nombre, apellidos, cédula de identidad, dirección, teléfono, celular, correo electrónico) o de los arrendatarios en su caso; registro de egresos del mes en curso, registro del estado de recaudación y registro de morosidad previa.</p>
        <p>c. Ingreso de la información al sistema: Una vez recibida la información señalada en el punto anterior, personal de LA EMPRESA procede a cargarla en bases de datos del sistema, proceso que demora aproximadamente tres días hábiles.</p>
        <p>d. Mantenciones: Todo tipo de mantención, reparación del software, será previamente notificado al CLIENTE con a lo menos cinco días hábiles de antelación. En tal caso el sistema podría quedar deshabilitado por a lo más un día hábil.</p>
        <p>e. Incidencias: Ante eventuales incidencias operativas que podrían ocurrir y que afecten el normal funcionamiento del sistema, LA EMPRESA se reserva el derecho de deshabilitar la plataforma por a lo más un día hábil para realizar las reparaciones correspondientes. Tales eventos pueden ser identificados por LA EMPRESA o el CLIENTE.</p>
        <p>f. Caso fortuito o fuerza mayor: Ante eventuales incidencias derivadas de factores externos a LA EMPRESA, tales como:</p>
        <p>desastres naturales, cortes de luz en dependencias del CLIENTE, falla en la conexión a internet u otras de índole menor, LA EMPRESA no tiene obligación de poseer ni tampoco implementar, planes de contingencia para dar continuidad al servicio. En tales circunstancias, LA EMPRESA monitoreará la pronta restauración del sistema. Sujeto a este escenario, toda información perdida o inconclusa es de responsabilidad del CLIENTE registrarla nuevamente en la plataforma. Es posible resolver dudas al número: +56232030883.</p>
        <p>TERCERO. Precio: El precio es determinado en base a la cantidad de comunidades que el CLIENTE administre usando el software y los servicios suscritos para cada una de ellas. Los planes mensuales que puede suscribir son los siguientes: Plan</p>
        <p>1: Sistema de gastos comunes por 2 UF mensuales por comunidad y por emisión de gasto común; Plan 2: Sistema de remuneraciones por 1 UF mensual por comunidad y por periodo mensual; Plan 3: Sistema de control de acceso por 1 UF mensual por comunidad, no incluye dispositivo. El precio de los planes es acumulativo y se debe considerar el valor de la UF a la fecha en que se realiza el pago. Lo último implica un monto en UF a pagar mensualmente igual a la suma de cada plan contratado por cada comunidad instalada en el sistema, que será facturado, cobrado y pagado mensualmente los 15 de cada mes, con la excepción del primer pago que se realizará el día en que se firma el contrato y corresponderá al primer mes emitido en el programa. El plan 1 considera la emisión de un mes de gasto común, emitir meses adicionales tienen un costo extra equivalente a la mensualidad de la comunidad a pagar por el CLIENTE. El plan 1 tiene un límite de 500 unidades registradas en el sistema, en caso de superar este número, el precio a pagar es de 1 UF adicional por cada 100 unidades extra. Todos los planes tienen IVA incluido. El pago se debe hacer por cheque nominativo o por transferencia a la Cuenta corriente: 00-160-20598-00 del Banco de Chile, a nombre de ManagCond SpA, RUT: 76.474.965-0. La transferencia debe ser notificada al Correo: <a href="mailto:facturacion@managcond.cl" target="_blank">facturacion@comunidadfeliz.cl</a> especificando el rut de quién contrata.</p>
        <p>CUARTO. Meses gratis por pago anual: En caso de pagar 10 mensualidades de todos los planes utilizados por una comunidad al contado, el CLIENTE tendrá de manera gratuita la décimo primer y décimo segunda mensualidad de esa comunidad.</p>
        <p>QUINTO. Instalación y puesta en marcha: Por cada comunidad que se adhiera, La EMPRESA instalará la comunidad 1 vez por un monto a pagar por el CLIENTE equivalente a una mensualidad. Adicionalmente, durante los primeros 30 días, el CLIENTE tiene derecho a solicitar una capacitación en nuestras instalaciones en los horarios informados por el ejecutivo de capacitaciones de la EMPRESA.</p>
        <p>SEXTO. Descuento primer mes: La primera factura de cada comunidad contratada considerará la primera mensualidad y el costo de instalación, donde la primera mensualidad tendrá costo 0, solo se cobrará el costo de instalación.</p>
        <p>SEPTIMO. Devolución: La política de devolución estará sujeta a la ley vigente, la EMPRESA hará devolución del dinero hasta 3 meses desde la fecha de contratación. Del monto a devolver, se descontará el servicio de instalación y las mensualidades devengadas. En caso de solicitar devolución, el CLIENTE pierde los beneficios de las clausulas cuatro y seis.</p>
        <p>OCTAVO. Uso de la información y privacidad: La EMPRESA tiene la obligación de asegurar la confidencialidad de la información almacenada en el sistema, para lo cual, no transferirá o cederá o de otra manera proveerá, salvo aquellos casos en que la legislación vigente lo indique o sean requeridos por la Justicia o algún otro órgano competente. La EMPRESA no usará información del sistema de manera individualizada con objetivos distintos a los que se informan al CLIENTE, sea este el Administrador o el Comité de la Comunidad que tenga el servicio contratado. La EMPRESA no tiene responsabilidad alguna ante la divulgación de información confidencial si esta es realizada por algún miembro de la comunidad, incluido el administrador del edificio. La veracidad de la información registrada en el sistema, y los posibles perjuicios derivados de su omisión, son de exclusiva responsabilidad del CLIENTE.</p>
        <p>NOVENO. Cambios de plan: El CLIENTE podrá dar de baja un plan notificando a través de un correo electrónico a contacto@comunidadfeliz.cl . El último mes que pagará corresponderá al mes en que fue notificada su salida, además deberá pagar las emisiones realizadas y no pagadas. Por ejemplo, si notifica el 1o de marzo, la última mensualidad a pagar será la de marzo.</p>
        <p>DÉCIMO. Terminación del contrato: El presente contrato tiene duración igual a 1 mes, pudiendo ser renovado por igual período. De no existir renovación, el CLIENTE podrá descargar un respaldo de toda la información registrada en el sistema.</p>
        <p>La EMPRESA se exime de responsabilidad dado el mal uso de la información y/o divulgación de datos confidenciales contenidos en este respaldo, si esto sucediera dado acto negligente del CLIENTE. La EMPRESA puede dar término del contrato unilateralmente.</p>
        <p>DÉCIMO PRIMERO. Anexo contrato: Junto con la suscripción de este contrato, el CLIENTE y la EMPRESA declaran como parte integrante del mismo, y por lo tanto esencial, el Anexo de Contrato No1, que contiene las especificaciones técnicas del sistema y los distintos planes.</p>
        <p>DÉCIMO SEGUNDO. Controversias: Cualquier dificultad o controversia que se produzca entre los contratantes respecto de la aplicación, interpretación, duración, validez o ejecución de este contrato o cualquier otro motivo, será sometida a arbitraje conforme al Reglamento Procesal de arbitrajes del Centro de Arbitraje y Mediación de Santiago, vigente al momento de solicitarlo. Las partes confieren poder especial irrevocable a la Cámara de Comercio de Santiago A.G., para que, a petición escrita de cualquiera de ellas, designe a un árbitro arbitrador en cuanto al procedimiento y de derecho en cuanto al fallo, de entre los integrantes del cuerpo arbitral del Centro de Arbitraje y Mediación de Santiago. En contra de las resoluciones del árbitro no procederá recurso alguno. El árbitro queda especialmente facultado para resolver todo asunto relacionado con su competencia y/o jurisdicción.</p>
        <p>DÉCIMO TERCERO. Información del sistema: La información del sistema es de propiedad de la comunidad que se administra, por lo que, en caso de terminación de relación laboral entre la comunidad y el administrador, esta podrá ser cedida, sin la necesidad del consentimiento el administrador, a la persona que el comité de administración de la comunidad estime conveniente.</p>
        <p>DÉCIMO CUARTO. Pago online Transbank: En caso de que la comunidad quiera incorporar el servicio de pago online, este se podrá habilitar siempre y cuando la comunidad realice las gestiones que Transbank le solicite. En caso de habilitarse el servicio, el software de ManagCond cobrará una comisión por transacción exitosamente realizada.</p>
        <p>DÉCIMO QUINTO. Pago online ManagCond: Este contrato funcionará como un mandato a la EMPRESA para recaudar los gastos comunes bajos las condiciones y precios establecidas al momento de activar la funcionalidad en el sitio web.</p>
        <p>DÉCIMO SEXTO. Actualizaciones: La EMPRESA puede actualizar unilateralmente este contrato el cual tendrá siempre una versión disponible en www.comunidadfeliz.cl/legal. En caso de modificar el contrato, el CLIENTE será notificado a través de su correo electrónico registrado en la plataforma, quien se dará por enterado y aceptará las condiciones en caso de no manifestar su voluntad de terminar el contrato.</p>
        <p>DÉCIMO SEPTIMO. Domicilio: Para los efectos de este contrato, las partes fijan su domicilio en la ciudad de Santiago de Chile.</p>
        <p>DÉCIMO OCTAVO. Ejemplares: El presente instrumento se firma en dos ejemplares del mismo tenor y fecha, quedando cada parte con uno de ellos.</p>
        <p>
            <br>
        </p>
        <p>‍</p>
        <h2>ANEXO CONTRATO Nº1</h2>
        <p>
            <br>
            Según lo señalado en la cláusula DÉCIMO PRIMERA, del Contrato de Prestación de Servicios de Software para la Administración de Edificios y Condominios, las partes han elevado a la calidad de esencial y como parte integrante del mismo, el siguiente Anexo de Contrato, el que contiene las especificaciones técnicas del sistema.</p>
        <p>PRIMERO. Descripción del sistema : El sistema consta de una plataforma tecnológica, accedida desde internet, denominada “ManagCond”, que apoya la administración de edificios y condominios bajo régimen de copropiedad. Los usuarios del sistema son el administrador del edificio y los copropietarios. Ambos acceden a la plataforma bajo un perfil correspondiente: perfil administrador, perfil copropietario.</p>
        <p><strong>SEGUNDO. Planes :</strong></p>
        <p><strong>1. PLAN 1: Sistema de gastos comunes</strong></p>
        <p>El sistema web presenta múltiples módulos los cuales están disponibles para su uso por el CLIENTE, los principales son:</p>
        <p>a. Perfiles de usuario: El perfil administrador puede ingresar a todos los módulos, además de administrar los permisos de los encargados. El encargado puede realizar acciones limitadas por el administrador. El perfil copropietario es similar al perfil administrador, sin embargo, no permite editar ni tampoco registrar datos, sólo posee atribuciones para visualizar información. b. Módulo copropietarios: Permite al administrador registrar los datos de los copropietarios de la comunidad y</p>
        <p>asignarlos a sus correspondientes unidades habitacionales. c. Módulo egresos: Permite al administrador registrar egresos originados a título de la comunidad y que están sujeto a prorrateo en gasto común. El registro consiste en la especificación del prestador, el monto de cobro, y el período de origen. El módulo permite registrar documentos de respaldo, entendiendo por ello: boletas, facturas, contratos, documentos de pago, u otros respaldos que abalen la prestación del servicio. El sistema permite visualizar egresos históricos y generar comprobantes útiles para el control interno del administrador. d. Módulo medidores: Permite al administrador registrar múltiples medidores, y para cada uno de ellos determinar el</p>
        <p>consumo por copropietario a partir del registro de lecturas mensuales. e. Módulo cobros especiales: Este módulo permite al administrador registrar cobros individuales para cada copropietario y que se cargan en el gasto común. Ejemplo de ellos son los cargos por uso o arriendo de espacios comunes. f. Módulo recaudación: Permite al administrador registrar el pago de los gastos comunes, subir comprobantes de pago y llevar un control de la morosidad. Este módulo permite al administrador registrar pagos anticipados o parciales de gasto común. El sistema registra los saldos a favor de cada copropietario y los aplica como descuento en el cálculo del próximo gasto común. g. Módulo gastos comunes: Permite al administrador el prorrateo automático de los egresos de la comunidad. El sistema soporta múltiples tipos de prorrateo por propiedad y según consumo individual (medidor). El módulo gastos comunes permite al administrador emitir mensualmente boletas digitales y enviarlas a las casillas de correo electrónico de cada copropietario. h. Módulo espacios comunes: Permite la administración de los espacios comunes y que los usuarios habilitados</p>
        <p>puedan arrendar, con o sin cargo al gasto común. i. Módulo Conserjería: Este módulo permite registrar las visitas y a qué departamento asisten. Adicionalmente, permite registrar la patente del vehículo que ingresa. El sub-módulo Bitácora, permite al administrador y a los usuarios designados, el registro de eventos o hitos dentro de la comunidad, asociados a una unidad.</p>
        <p><strong>2. PLAN 2: Remuneraciones</strong></p>
        <p>Este módulo permite emitir liquidaciones de sueldo y finiquitos del personal de la comunidad. Adicionalmente, cobra el valor de esta remuneración automáticamente en el gasto común (si corresponde) y permite generar respaldos de la documentación firmada de manera digital, la exportación masiva de datos y el libro de remuneraciones según el formato establecido por la EMPRESA. Adicionalmente, la importación de la planilla de sueldos a Previred, el cual está certificado por esta institución.<br>
        </p>
    </div>

    <div class="container-21 w-container">
        <div class="legal w-richtext">
            <h2>TERMINOS Y CONDICIONES DE SERVICIO<br>
                “SERVICIOS LEGALES PARA LA ADMINISTRACION DE EDIFICIOS Y CONDOMINIOS”</h2>
            <h2>‍</h2>
            <p>Mediante la utilización de nuestros Servicios usted está aceptando estas condiciones. Por favor, léalas detenidamente.<strong><br>
                <br>
                PRIMERO. Descripción del servicio:</strong> El siguiente documento tiene por objeto la prestación de servicios legales que suministra LegalChile S.A. Para estos efectos, LegalChile ha desarrollado un plan legal con coberturas especialmente orientadas a satisfacer las necesidades jurídicas de las comunidades y empresas asociadas a ManagCond desde ahora indistintamente “LA EMPRESA” o “ComunidadFeliz.cl”, todo ello en la forma, términos y condiciones que se especifican en el presente documento y su anexo. Al aceptar estos términos, la comunidad y/o empresa asociada, desde ahora indistintamente el “CLIENTE”, declara tener total conocimiento de los detalles y alcances del servicio contratado.<strong><br>
                    <br>
                    SEGUNDO. Obligaciones de las partes</strong></p>
            <p><strong>a. Implementación del sistema:</strong> LegalChile es una plataforma de servicios legales a distancia. Para su acceso el CLIENTE debe considerar un computador con conexión a internet y un navegador web, o en su defecto un teléfono.</p>
            <p><strong>b. Incidencias:</strong> Ante eventuales incidencias operativas que podrían ocurrir y que afecten el normal funcionamiento del sistema, LA EMPRESA se reserva el derecho de deshabilitar la plataforma por a lo más un día hábil para realizar las reparaciones correspondientes. Tales eventos pueden ser identificados por LA EMPRESA o el CLIENTE.</p>
            <p><strong>c. Caso fortuito o fuerza mayor:</strong> Ante eventuales incidencias derivadas de factores externos a LA EMPRESA, tales como: desastres naturales, cortes de luz en dependencias del CLIENTE, falla en la conexión a internet u otras de índole menor, LA EMPRESA no tiene obligación de poseer ni tampoco implementar, planes de contingencia para dar continuidad al servicio. En tales circunstancias, LA EMPRESA monitoreará la pronta restauración del sistema. Sujeto a este escenario, toda información perdida o inconclusa es de responsabilidad del CLIENTE comunicarla nuevamente a LegalChile. Es posible resolver dudas al número: +56 2 2938 1880.<br>
                <br>
                <strong>TERCERO. Precio:</strong> El precio a pagar corresponde a la suscripción del servicio de manera semestral, y es determinado en base a la cantidad de comunidades que suscriba el CLIENTE. El precio para las comunidades que tienen contratado el software de ComunidadFeliz.cl es de 9UF/semestre, mientras que para aquellas que no tienen contratado el software de ComunidadFeliz.cl es de 12UF/semestre. Este precio deberá ser pagado previo a la habilitación del Servicio Legal para Comunidades. El pago se debe hacer por cheque nominativo o por transferencia a la cuenta corriente 00-160-20598-00 del Banco de Chile, a nombre de ManagCond SpA, RUT: 76.474.965-0. La transferencia debe ser notificada al correo contacto@comunidadfeliz.cl especificando el rut de quién contrata.<strong><br>
                    <br>
                    CUARTO. Habilitación del Servicio:</strong> Por cada comunidad que se adhiera, La EMPRESA informará a LegalChile S.A. para que comience con la prestación del Servicio Legal para Comunidades.</p>
            <p>El servicio se habilitará a partir del 2 de Septiembre de 2019. Una vez que el cliente contrate, el servicio se habilitará a más tardar 5 días hábiles luego del pago del servicio, siempre y cuando esta fecha sea igual o posterior a la de habilitación del servicio.<br>
                <br>
                <strong>QUINTO. Devolución:</strong> La política de devolución estará sujeta a la ley vigente, la EMPRESA no realizará devoluciones.<br>
                <br>
                <strong>SEXTO. Cambios de plan:</strong> El CLIENTE podrá dar de baja un plan notificando a través de un correo electrónico a contacto@comunidadfeliz.cl. En dicho caso, el plan será descontinuado una vez alcanzada la siguiente fecha de renovación.<strong><br>
                    <br>
                    SÉPTIMO. Terminación del servicio:</strong> El servicio ofrecido tiene duración igual a 6 meses, pudiendo ser renovado por igual período. La EMPRESA puede dar término al servicio unilateralmente, en cuyo caso deberá restituir al CLIENTE el costo proporcional del servicio en los meses no utilizados.<strong><br>
                        <br>
                        OCTAVO. Anexo:</strong> Junto con la suscripción de este documento, el CLIENTE y la EMPRESA declaran como parte integrante del mismo, y por lo tanto esencial, el Anexo No1, que contiene las especificaciones técnicas del plan de Servicios Legales para Comunidades.<br>
                <br>
                <strong>NOVENO. Actualizaciones:</strong> La EMPRESA puede actualizar unilateralmente este documento. En caso de modificar este documento, el CLIENTE será notificado a través de su correo electrónico registrado en la plataforma, quien se dará por enterado y aceptará las condiciones en caso de no manifestar su voluntad de terminar el servicio.<br>
                <br>
                <strong>DÉCIMO. Domicilio: </strong>Para los efectos de este documento, las partes fijan su domicilio en la ciudad de Santiago de Chile.<br>
                ‍</p>
            <p><strong>ANEXO N°1</strong></p>
            <p>Según lo señalado en la cláusula OCTAVA, del los T&amp;C de Servicios Legales para la Administración de Edificios y Condominios, las partes han elevado a la calidad de esencial y como parte integrante del mismo, el siguiente anexo, el que contiene las especificaciones técnicas del sistema.</p>
            <p><strong>I.- Descripción de la cobertura para la Comunidad</strong></p>
            <p>Cubre el 100% de los honorarios de abogados de LegalChile en las siguientes materias y gestiones</p>
            <p><strong>Consultas</strong></p>
            <p>El representante de la Comunidad podrá efectuar consultas telefónicas relativas a todo tipo de materias legales relacionadas con la comunidad, tales como:</p>
            <p>1. Normas legales sobre copropiedad y otras normas que rigen a las comunidades:<br>
                - Comité de administración<br>
                - Quorum para sesionar<br>
                - Nombramiento de administrador<br>
                - Materias objeto de asambleas ordinarias o extraordinarias.</p>
            <p>2. Sentido y alcance de las normas contenidas en Ley de urbanismo y Construcción y su aplicación a la Comunidad.</p>
            <p>3. Sobre aplicación de reglamento de copropiedad</p>
            <p>4. Derechos y obligaciones que generan para la Comunidad los contratos celebrados por sus representantes:<br>
                - Compraventa de bienes y servicios<br>
                - Arrendamiento de espacios comunes<br>
                - Comodato</p>
            <p>5. Facultades y responsabilidades legales del administrador y de los miembros del comité de administración.</p>
            <p>6. Facultades del juez de Policía local en relación con conflictos suscitados en la Comunidad.</p>
            <p>7. Responsabilidad civil extracontractual de la Comunidad y del Comité de Administración en caso de daños sufridos por terceros.</p>
            <p><strong>Asesorías</strong></p>
            <p>El representante de la Comunidad podrá solicitar a LegalChile la revisión y redacción de los siguientes documentos jurídicos y contratos relacionados con la Comunidad:</p>
            <p>- Reglamento de copropiedad<br>
                - Contrato de arrendamiento de espacios comunes<br>
                - Cualquier otro contrato en que participe la comunidad</p>
            <p><strong>Juicios</strong></p>
            <p>El representante de la Comunidad podrá solicitar a LegalChile la representación judicial en las siguientes causas iniciadas por la Comunidad o por terceros en contra de ésta:</p>
            <p><strong>- Juicios Civiles:</strong>‍</p>
            <p>- Demandas de arrendamiento<br>
                - Demandas de indemnización de perjuicios por responsabilidad civil extracontractual.<br>
                - Cobro de gastos comunes<br>
                - Otros juicios civiles</p>
            <p><strong>- Juicios Penales:</strong></p>
            <p>- Por delitos de robo o hurto; estafas y cualquier otro delito que afecte a la Comunidad</p>
            <p><strong>- Juicios Laborales:</strong></p>
            <p>- Por despido injustificado<br>
                - Cobro de prestaciones laborales<br>
                - Cualquier otra acción laboral que afecte a la Comunidad</p>
            <p><strong>- Juicios de Policía Local:</strong></p>
            <p>- Ley de Urbanismo y Construcción<br>
                - Ley de Copropiedad inmobiliaria</p>
            <p><strong>II.- Descripción de la cobertura para el Administrador</strong></p>
            <p>Cubre el 100% de los honorarios de abogados de LegalChile en las siguientes materias y gestiones</p>
            <p><strong>Consultas</strong></p>
            <p>El administrador de la Comunidad podrá efectuar consultas telefónicas relativas a todo tipo de materias legales relacionadas con la Comunidad que administra, tales como:</p>
            <p>1. Normas legales sobre copropiedad y otras normas que rigen a las comunidades</p>
            <p>2. Cobro de gastos comunes</p>
            <p>3. Ley de Urbanismo y Construcción y su aplicación a la Comunidad.</p>
            <p>4. Normas y regulación aplicada por la Superintendencia de Electricidad y Combustibles (SEC) en edificios y comunidades.</p>
            <p>5. Normas Laborales y Previsionales aplicables a los trabajadores contratados por la Comunidad.</p>
            <p>6. Disposiciones Municipales que deben cumplirse por las comunidades y sanciones en casos de incumplimiento de las mismas.</p>
            <p>7. Normas sobre seguros que deban ser contratados en forma voluntaria u obligatoria por la Comunidad.</p>
            <p>8. Aplicaciones de la Ley de Protección al Consumidor.</p>
            <p>9. Contratos de arrendamiento de espacios comunes</p>
            <p>10. Facultades del juez de Policía local en relación con conflictos suscitados entre comuneros o de estos con el administrador.</p>
            <p>11. Responsabilidad civil extracontractual del Administrador en caso de daños sufridos por terceros.</p>
            <p><strong>Asesorías</strong></p>
            <p>El administrador de la Comunidad podrá solicitar a LegalChile la revisión y redacción de los siguientes documentos jurídicos y contratos relacionados con la Comunidad:</p>
            <p>- Compraventa de bienes muebles e insumos<br>
                - Contratos de Prestación de servicios de terceros a la comunidad<br>
                - Contratos de trabajo de empleados de la Comunidad<br>
                - Modelo de finiquito laboral<br>
                - Modelo de cobranza extrajudicial de gastos comunes</p>
            <p><strong>Juicios</strong></p>
            <p>El administrador de la Comunidad podrá solicitar a LegalChile la representación judicial en causas iniciadas por terceros en su contra en su calidad de administrador de la Comunidad:</p>
            <p>- Juicios Civiles<br>
                - Demandas de indemnización de perjuicios por responsabilidad civil extracontractual.<br>
                - Juicios Penales<br>
                - Denuncias interpuestas en su contra por supuestos delitos de lesiones o daños</p>
            <p><strong>III.- Cobertura (Comunidad y Administrador)</strong></p>
            <p>• Consultas : Sin costo<br>
                • Asesorías : Sin costo<br>
                • Juicios : Costo único UF8.5 por juicio</p>
            <p>* Todas las prestaciones sin límite de eventos.</p>
            <p><strong>IV.- Exclusiones</strong></p>
            <p>▪ Atención de asuntos ocurridos antes de la entrada en vigencia del contrato<br>
                ▪ Temas no relacionados directamente con la Comunidad<br>
                ▪ Representación del Administrador en contra de la Comunidad<br>
                ▪ Conflictos entre la Comunidad y Corredoras o Compañías de Seguro, Bancos e Instituciones Financieras y cualquier conflicto con ManagCond.<br>
                ▪ Asistencia a asambleas<br>
                ▪ Aquellas materias legales que estén regidas o sometidas a una legislación que no sea la chilena.<br>
                ▪ La asistencia a audiencias de control de detención o a cualquier audiencia o comparendo que hayan sido informadas con menos de 48 horas hábiles antes de su celebración.<br>
                ▪ Todos los gastos que generen las gestiones, serán de cargo del cliente. Se entiende por tales el pago de honorarios de notaría, conservadores, archiveros o receptores judiciales; de aranceles de Registro Civil, de Impuestos, y en general cualquier otro gasto que genere la gestión profesional, distintos del honorario de abogados y procuradores.</p>
            <p><strong>V.- Conflicto de Interés</strong></p>
            <p>Existirá conflicto de interés toda vez que LegalChile sea requerido para la representación judicial de dos o más partes en disputa, cuando estas partes tengan un plan vigente que incluya la cobertura judicial correspondiente a ese litigio.</p>
            <p>Estos casos se resolverán de la siguiente manera:</p>
            <p>- Si el conflicto se plantea entre dos o más clientes, LegalChile, estará obligada a instar por la mediación o conciliación entre las partes, y si ésta fracasa, no podrá ni deberá intervenir en representación de ninguno de los involucrados.</p>
            <p>- Sin perjuicio de lo anterior, LegalChile, junto con poner en conocimiento de los involucrados esta situación, les informará que pagará el honorario de los abogados que contraten para su representación en este caso, hasta el monto del porcentaje del valor del arancel cubierto por LegalChile para ese tipo de juicio, de acuerdo al plan que cada uno mantenga. Para estos efectos, el abogado del cliente deberá hacer llegar a LegalChile la boleta de honorarios correspondiente, conjuntamente con el escrito de patrocinio y poder en la causa, con certificado de recepción del tribunal.</p>
            <p><strong>VI.- Cómo utilizar el servicio</strong></p>
            <p>Número Único Nacional 228874000<br>
                Internet www.legalchile.cl<br>
            </p>
        </div>
    </div>

    <div class="container-21 w-container">
        <div id="pago-en-linea" class="legal w-richtext">
            <p>Términos y Condiciones Pago en Línea</p>
            <p><strong>Actualizado:</strong> 1 de agosto de 2020.</p>
            <p>El presente sitio web, ubicado en la dirección www.ComunidadFeliz.cl ofrece servicios de recaudación de pagos a través de una Plataforma de Pagos –en adelante la <strong>"Plataforma"</strong>- a la cual se puede acceder a través del dominio ComunidadFeliz.cl –en adelante el <strong>"Sitio"</strong>-, ambos provistos por <strong>ManagCond SpA</strong>,- en adelante <strong>"ManagCond"</strong> o <strong>"La Empresa"</strong>.</p>
            <p>La <strong>Empresa</strong> declara que la <strong>Plataforma</strong> y su acceso se encuentran condicionados a la aceptación completa por parte del <strong>Usuario</strong> de los términos y condiciones que se expresan a continuación:</p>
            <ol role="list">
                <li>El acceso a la <strong>Plataforma</strong>, en forma directa o indirecta, su uso y/o la descarga de información contenida en ella supone que el <strong>Usuario</strong> de la misma acepta los presentes términos y condiciones en todas sus partes. Quien no aceptare los presentes términos y condiciones, deberá abstenerse de acceder a la <strong>Plataforma</strong>, ya sea directa o indirectamente y de utilizar cualquier información o servicio provisto por la misma.</li>
                <li>Siempre que en estos Términos y Condiciones se haga referencia al <strong>"Usuario"</strong> se entenderá por tal a cualquier persona natural o jurídica, agrupación sin personalidad legal, o representante en cualquier forma de los mismos, que use los servicios y/o información contenidas en la <strong>Plataforma</strong>. El <strong>Usuario</strong> estará sujeto a los términos y condiciones que rigen para la utilización de la <strong>Plataforma</strong> y que se describen en el presente documento.</li>
                <li>Los <strong>Usuarios</strong> de la <strong>Plataforma</strong> son de dos tipos: (i) el <strong>Usuario</strong> que solicita el servicio de pago o recaudación de la <strong>Plataforma</strong>, en adelante <strong>"Usuario Mandante"</strong>, y (ii) el <strong>Usuario</strong> que paga en la <strong>Plataforma</strong>, en adelante <strong>"Usuario Pagador"</strong>.</li>
                <li>En estas Condiciones Generales se describen los derechos y responsabilidades del <strong>Usuario</strong> y de <strong>ManagCond</strong> por utilizar el servicio de pago o recaudación a través de Internet, al combinar: (i) dispositivos móviles (smartphones y otros) y/o dispositivos tradicionales (Computador personal, Notebook y otros), (ii) el uso del cupo o capacidad de pago que el <strong>Usuario</strong> mantenga en cualquier medio de pago que acepte la <strong>Plataforma</strong>, (iii) tecnología web, el <strong>Sitio</strong> y cualquier producto o servicio relacionado que ofrezca la <strong>Plataforma</strong>.</li>
            </ol>
            <p>El Usuario declara en este acto haber leído, entender y aceptar todas las condiciones establecidas en estas Condiciones Generales, previo a su registro como <strong>Usuario</strong> de la <strong>Plataforma</strong>.<br>
                <br>
                <strong>CUALQUIER PERSONA QUE NO ACEPTE ESTOS TÉRMINOS Y CONDICIONES GENERALES, LOS CUALES TIENEN UN CARÁCTER OBLIGATORIO Y VINCULANTE, DEBERÁ ABSTENERSE DE UTILIZAR LA PLATAFORMA.</strong></p>
            <p>1.- Registro</p>
            <ol role="list">
                <li><strong>Registro</strong>. Todo <strong>Usuario Mandante</strong> que desee utilizar el Servicio de Pago o Recaudación debe, a través del <strong>Sitio</strong>, registrarse en la <strong>Plataforma</strong>, con lo cual declara aceptar íntegramente estas Condiciones Generales. Para registrarse es obligatorio completar el formulario de registro en todos sus campos con datos válidos e información personal exacta, precisa y verdadera ("Datos Personales"). El <strong>Usuario</strong> asume el compromiso de actualizar los Datos Personales conforme resulte necesario. <strong>ManagCond</strong> NO se responsabiliza por la certeza de los Datos Personales provistos por sus usuarios. Los Usuarios garantizan y responden, en cualquier caso, de la veracidad, exactitud, integridad, vigencia y autenticidad de los Datos Personales ingresados. <strong>Toda la información y los Datos Personales ingresados por el Usuario tienen carácter de declaración jurada</strong>. <strong>ManagCond</strong> se reserva el derecho de rechazar una solicitud de registro o de cancelar o suspender, temporal o definitivamente una cuenta sin expresión de causa, y especialmente, en caso de detectar incongruencias o inconsistencias en la información provista por un <strong>Usuario</strong> o en caso de detectar actividades sospechosas, sin que tal decisión genere para el <strong>Usuario</strong> derechos de indemnización o resarcimiento.</li>
                <li><strong>El Proceso de Mandato de Recaudación.</strong></li>
            </ol>
            <ol role="list">
                <li>Una vez inscrito en la <strong>Plataforma</strong>, cada vez que el <strong>Usuario Mandante</strong> notifique la emisión de un gasto común a través del <strong>Sitio</strong>, el <strong>Usuario Mandante</strong> emitirá automáticamente una Orden de Pago o Recaudación dirigida a <strong>ManagCond</strong>, para que éste recaude en su nombre, estableciendo en dicha orden, al menos: correo electrónico de cada <strong>Usuario Pagador</strong>, tipo de pago o recaudación, descripción, monto y moneda del servicio que pagará a <strong>ManagCond</strong> por el uso de la <strong>Plataforma</strong>.</li>
                <li>La <strong>Plataforma</strong> creará una Notificación de Pago o Recaudación al <strong>Usuario Pagador</strong>, identificado en la Orden de Pago o Recaudación, para que éste proceda al pago, simultáneamente le enviará un correo electrónico con la información y registrará este hecho en la <strong>Plataforma</strong>.</li>
                <li>La <strong>Plataforma</strong> permitirá al <strong>Usuario Pagador</strong> que éste pague usando el medio de pago que él disponga y la Plataforma acepte, desde cualquier computador personal o dispositivo móvil conectado a Internet, permitiendo la realización de transacciones con dichos medios de pago en cualquier tiempo y lugar gracias a la ubicuidad de los dispositivos móviles.</li>
                <li>Una vez que el <strong>Usuario Pagador</strong> paga a través de la <strong>Plataforma</strong> y <strong>ManagCond</strong> recauda en nombre del <strong>Usuario Mandante</strong>, la <strong>Plataforma</strong> registra este hecho en el <strong>Sitio</strong>.</li>
                <li>La fecha estimada de abono es 2 días hábiles bancarios para transacciones realizadas con tarjetas de débito y crédito.</li>
                <li>En caso de existir problemas derivados de acciones de terceros que impliquen postergar la fecha estimada de abono, la <strong>Plataforma</strong> enviará un correo electrónico informando de la nueva fecha estimada de abono en la cuenta bancaria del <strong>Usuario Mandante</strong>.</li>
                <li>Una vez que se cumpla la fecha de pago, no existiendo problemas derivados de acciones de terceros, la <strong>Plataforma</strong> enviará a pago la recaudación, descontada su comisión, a la cuenta bancaria registrada por el <strong>Usuario Mandante</strong> en el <strong>Sitio</strong>, los datos de la cuenta bancaria ingresados deben estar necesariamente asociados al rol único tributario (Rut) de la <strong>Comunidad</strong> que el <strong>Usuario Mandante</strong> administra. Simultáneamente, generará un correo electrónico al <strong>Usuario Mandante</strong> informando que se ha enviado a pago lo recaudado, descontada la comisión por los servicios de la Plataforma.</li>
                <li>En el caso de que la recepción del pago sea rechazada por el banco del <strong>Usuario Mandante</strong>, la <strong>Plataforma</strong> le enviará un correo electrónico al <strong>Usuario Mandante</strong> informando del rechazo. Será responsabilidad exclusiva del <strong>Usuario Mandante</strong> hacer todas las gestiones ante su banco a objeto de destrabar la recepción del dinero, informando a <strong>ManagCond</strong> a través de la <strong>Plataforma</strong> de la solución del problema generado.</li>
                <li>Toda transacción ocurrida en la <strong>Plataforma</strong> está sujeta un análisis de comportamiento, en particular, cada nuevo <strong>Usuario Mandante</strong> registrado en la <strong>Plataforma</strong> mandata a ManagCond para que supervise de manera particular sus transacciones.<br>
                    Con el fin de que ManagCond cumpla con su <strong>servicio de pago o recaudación</strong> y, en el caso de que ManagCond en la ejecución de su proceso de supervisión de transacciones ocurridas en la <strong>Plataforma</strong>, detecte una actividad que tenga comportamiento no normal, o una transacción sea sospechosa de un acto ilícito o el contenido de la transacción investigada no se ajuste a estos <strong>Términos y Condiciones</strong>, entonces, el <strong>Usuario Mandante</strong>:</li>
            </ol>
            <ol role="list">
                <li>autoriza a <strong>ManagCond</strong> investigar en detalle sus transacciones,</li>
                <li>se obliga a entregar con la máxima celeridad toda documentación o información que <strong>ManagCond</strong> le solicite relativa a las transacciones efectuadas o antecedentes relativos a su negocio,</li>
                <li>autoriza a <strong>ManagCond</strong> retener los montos involucrados en ellas, mientras dure la investigación,</li>
                <li>mandata a <strong>ManagCond</strong> a que le transfiera los dineros de las transacciones investigadas una vez que el <strong>Usuario Pagador</strong> informa por escrito a ManagCond o hace llegar a ManagCond documentación donde se consigna la conformidad con el servicio brindado y/o el producto pagado.</li>
            </ol>
            <ol role="list">
                <li>El Proceso de <strong>Mandato de Pago</strong>.</li>
            </ol>
            <ol role="list">
                <li>En este caso el usuario <strong>Mandante</strong> corresponde al usuario <strong>Pagador.</strong></li>
                <li>El usuario <strong>Mandante</strong> instruye el pago de una cuenta de gasto común, seleccionando al <strong>receptor final</strong> de dicho pago entre las comunidades usuarias del <strong>Sitio</strong>.</li>
                <li>La <strong>Plataforma</strong> permitirá al <strong>Usuario Mandante </strong>que éste pague usando el medio de pago que él disponga y la Plataforma acepte, desde cualquier computador personal o dispositivo móvil conectado a Internet, permitiendo la realización de transacciones con dichos medios de pago en cualquier tiempo y lugar gracias a la ubicuidad de los dispositivos móviles.</li>
                <li>Una vez que el <strong>Usuario Mandante </strong>paga a través de la <strong>Plataforma</strong> y <strong>ManagCond</strong> recauda en nombre del <strong>receptor final</strong>, la <strong>Plataforma</strong> registra este hecho en el <strong>Sitio</strong>.</li>
                <li>La fecha estimada de abono es 2 días hábiles bancarios para transacciones realizadas con tarjetas de débito y crédito.</li>
                <li>En caso de existir problemas derivados de acciones de terceros que impliquen postergar la fecha estimada de abono, la <strong>Plataforma</strong> enviará un correo electrónico informando de la nueva fecha estimada de abono en la cuenta bancaria del <strong>receptor final</strong>.</li>
                <li>Una vez que se cumpla la fecha de pago, no existiendo problemas derivados de acciones de terceros, la <strong>Plataforma</strong> enviará a pago la recaudación, descontada su comisión, a la cuenta bancaria registrada por el <strong>receptor final</strong> en el <strong>Sitio</strong>, los datos de la cuenta bancaria ingresados deben estar necesariamente asociados al rol único tributario (Rut) de la <strong>Comunidad</strong> correspondiente al <strong>receptor final</strong>. Simultáneamente, generará un correo electrónico al <strong>receptor final </strong>informando que se ha enviado a pago lo recaudado, descontada la comisión por los servicios de la Plataforma.</li>
                <li>En el caso de que la recepción del pago sea rechazada por el banco del <strong>receptor final</strong>, la <strong>Plataforma</strong> le enviará un correo electrónico al <strong>receptor final </strong>informando del rechazo. Será responsabilidad exclusiva del <strong>receptor final </strong>hacer todas las gestiones ante su banco a objeto de destrabar la recepción del dinero, informando a <strong>ManagCond</strong> a través de la <strong>Plataforma</strong> de la solución del problema generado.</li>
                <li>Toda transacción ocurrida en la <strong>Plataforma</strong> está sujeta un análisis de comportamiento, en particular, cada nuevo <strong>receptor final </strong>registrado en la <strong>Plataforma</strong> mandata a ManagCond para que supervise de manera particular sus transacciones.<br>
                    Con el fin de que ManagCond cumpla con su <strong>servicio de pago o recaudación</strong> y, en el caso de que ManagCond en la ejecución de su proceso de supervisión de transacciones ocurridas en la <strong>Plataforma</strong>, detecte una actividad que tenga comportamiento no normal, o una transacción sea sospechosa de un acto ilícito o el contenido de la transacción investigada no se ajuste a estos <strong>Términos y Condiciones</strong>, entonces, el <strong>Usuario Mandante</strong>:</li>
            </ol>
            <ol role="list">
                <li>autoriza a <strong>ManagCond</strong> investigar en detalle sus transacciones,</li>
                <li>se obliga a entregar con la máxima celeridad toda documentación o información que <strong>ManagCond</strong> le solicite relativa a las transacciones efectuadas o antecedentes relativos a su negocio,</li>
                <li>autoriza a <strong>ManagCond</strong> retener los montos involucrados en ellas, mientras dure la investigación.</li>
            </ol>
            <ol start="4" role="list">
                <li><strong>Acceso</strong>. El Usuario accederá al <strong>Sitio</strong> mediante el ingreso de su dirección de correo electrónico (e-mail) y su clave de seguridad personal ("Clave de Ingreso"). El Usuario se obliga a mantener la confidencialidad de todas sus Claves. En virtud de ello, el Usuario será el único y exclusivo responsable por todas las operaciones efectuadas en su nombre en el <strong>Sitio</strong>.</li>
                <li><strong>El pago y terceros relevantes</strong>. El pago se realiza utilizando la <strong>Plataforma</strong> y los servicios de Operadores de Medios de Pago proveedores de la <strong>Plataforma</strong>, eligiendo uno de estos servicios en función de su disponibilidad en la <strong>Plataforma</strong> y la decisión el <strong>Usuario Pagador</strong> al momento de realizar el pago.</li>
                <li><strong>Moneda</strong>. Cualquier referencia a dinero en la <strong>Plataforma</strong> se entenderá hecha en la moneda de curso legal -pesos chilenos- a menos que en la plataforma se indique específicamente la moneda de curso legal de otro país.&nbsp;</li>
                <li><strong>Usuarios Mandantes</strong>. El registro de los Usuarios Mandantes se realiza con el fin de que <strong>ManagCond</strong> disponga de la información bancaria necesaria para que el <strong>Usuario Mandante</strong> reciba el pago en su cuenta bancaria, pudiendo registrar un tipo de cuenta aceptado por la <strong>Plataforma</strong>. La <strong>Plataforma</strong> obliga al <strong>Usuario Mandante</strong> a ingresar los datos necesarios para realizar una transferencia electrónica: correo electrónico válido y una clave secreta asociada a él, Nombre(s) y Apellido(s), RUT, Banco, Tipo de cuenta, Identificación de la cuenta (donde el <strong>Usuario Mandante</strong> recibirá los pagos descontado el monto del servicio de <strong>ManagCond</strong>), adicionalmente, la <strong>Plataforma</strong> solicita con carácter de obligatorio un número telefónico de contacto válido. En el caso de que el <strong>Usuario Mandante</strong> desee que <strong>ManagCond</strong> le emita una factura de venta en lugar de una boleta de venta por los servicios prestados a través de la <strong>Plataforma</strong>, el <strong>Usuario Mandante</strong> está obligado a agregar a su registro: Razón social (si corresponde), Dirección física, Giro, Rut e indicar en la <strong>Plataforma</strong> que desea recibir una factura. La periodicidad con que <strong>ManagCond</strong> emitirá y enviará al Usuario Mandante la boleta o factura será mensual, siendo esta emitida a más tardar el último día de cada mes.</li>
                <li><strong>Usuario Pagador</strong>. El registro del <strong>Usuario Pagador</strong> exige ingresar un correo electrónico valido y una clave secreta asociado a él.</li>
            </ol>
            <p>2.- Mandato</p>
            <ol role="list">
                <li><strong>Mandato Irrevocable</strong>. El <strong>Usuario Mandante</strong> otorga mandato comercial irrevocable en los términos establecidos en el artículo 241 del Código de Comercio a <strong>ManagCond</strong> para que éste proceda a recaudar los dineros informados por el <strong>Usuario Mandante</strong> a través de una la Orden de Pago o Recaudación emitida por él, al momento de usar el servicio de pago o recaudación. <strong>ManagCond</strong> está facultado para depositar los dineros del producto de la recaudación en la cuenta bancaria que haya registrado el <strong>Usuario Mandante</strong>, descontando previamente el dinero que corresponde a <strong>ManagCond</strong> por pago de sus servicios de recaudación.</li>
                <li><strong>Alcance de responsabilidad</strong>. <strong>ManagCond</strong> no será responsable ni garantizará el cumplimiento de las obligaciones que hubiesen asumido y acordado los <strong>Usuarios</strong> entre si o con terceros en relación al pago o recaudación de los dineros realizados a través de la <strong>Plataforma</strong>. El <strong>Usuario</strong> reconoce y acepta que al realizar transacciones con otros <strong>Usuarios</strong> o terceros lo hace por su propia voluntad, ajeno al servicio de pago o recaudación provisto por la <strong>Plataforma</strong>, prestando su consentimiento libremente y bajo su propio riesgo y responsabilidad. En ningún caso <strong>ManagCond</strong> será responsable por lucro cesante, o por cualquier otro daño y/o perjuicio que haya podido sufrir el <strong>Usuario</strong> debido a las transacciones realizada.<br>
                    En virtud que <strong>ManagCond</strong> es ajeno a la obligación que dio origen a la Orden de Pago o Recaudación, <strong>ManagCond</strong> no será responsable ni verificará las causas, importe o cualquier otra circunstancia relativa a dicha Orden de Pago o Recaudación, así como respecto de la existencia, calidad, cantidad, funcionamiento, estado, integridad o legitimidad de los bienes o servicios ofrecidos, adquiridos o enajenados por los Usuarios. La <strong>Plataforma</strong> sólo facilita la recaudación de los pagos generados en una transacción anterior al servicio prestado por ella.<br>
                    En caso que uno o más Usuarios o algún tercero inicien cualquier tipo de reclamo o acciones legales contra otro u otros Usuarios, todos y cada uno de los Usuarios involucrados en dichos reclamos o acciones eximen de toda responsabilidad a <strong>ManagCond</strong> y a sus directores, gerentes, empleados, agentes, operarios, representantes y apoderados y renuncian a ejercer las acciones legales de cualquier naturaleza que les pudieran corresponder.&nbsp;</li>
            </ol>
            <p>3.- Información y correos electrónicos falsos</p>
            <p>Toda información debe ser siempre verificada por el <strong>Usuario</strong> a través del <strong>Sitio</strong> accediendo con su dirección de correo electrónico (e-mail) y clave de seguridad personal.<br>
                <strong>ManagCond</strong> no será responsable por las conductas del Usuario que se originen o vinculen con información contenida en correos electrónicos falsos o que aparenten provenir de <strong>ManagCond, </strong>el<strong> Sitio,</strong> o la <strong>Plataforma</strong> que sean, enviados por terceros sin relación con <strong>ManagCond</strong> ni con sus sociedades relacionadas; como así tampoco responderán por las consecuencias dañosas de tales conductas, ni por la circulación de los mencionados correos electrónicos falsos.</p>
            <p>4.- Condiciones Generales de Contratación</p>
            <ol role="list">
                <li><strong>Capacidad</strong>. Sólo podrán emitir órdenes de pago o recaudación y contratar la utilización de servicios de recaudación aquellas personas que tengan capacidad legal para contratar y estén debidamente registrados como Usuarios en el <strong>Sitio</strong>. No podrán registrarse ni utilizar los servicios personas que no tengan capacidad para contratar o aquellos Usuarios que hayan sido suspendidos o inhabilitados en el <strong>Sitio</strong> temporal o definitivamente.</li>
                <li><strong>Declaraciones del Usuario</strong>. <strong>Usos Prohibidos</strong>. El <strong>Usuario</strong> manifiesta que el objeto por el cual se celebra la Orden de Pago o Recaudación no infringe ninguna ley aplicable, ni es por un servicio, venta o transmisión que está prohibida por la ley o por estos Términos y Condiciones Generales, tales como y sin limitarse a: (i) juegos de azar, apuestas, etc.; (ii) tráfico de armas, de personas, de animales, etc.; (iii) lavado de dinero y/o terrorismo; (iv) pornografía, prostitución o pedofilia; y/o (v) cualquier tipo de actividad que pueda ser considerada fraudulenta o ilegal o sospechosa de serlo.<br>
                    El Usuario no utilizará la <strong>Plataforma,</strong> ni el <strong>Sitio,</strong> para transmitir material que constituya un delito o bien que pueda dar lugar, directa o indirectamente a responsabilidades civiles o que infrinjan estos Términos y Condiciones Generales.<br>
                    Si <strong>ManagCond</strong> considera que hay una sospecha o indicio de la utilización de la <strong>Plataforma</strong> para alguna actividad prohibida por la ley o estos Términos y Condiciones Generales, podrá rechazar, cancelar o suspender una Orden de Pago o Recaudación, y/o bloquear temporalmente el acceso a un <strong>Usuario</strong> y/o la utilización o disponibilidad de funcionalidades y/o cancelar definitivamente un Registro de <strong>Usuario</strong> En tal caso, el <strong>Usuario</strong> responderá por los daños y perjuicios que pueda haber ocasionado a <strong>ManagCond</strong> sus controlantes, controladas, filiales o subsidiarias, funcionarios, empleados, directores, agentes, y/o empleados, a cuyos efectos <strong>ManagCond</strong> se reserva el derecho de iniciar las acciones judiciales o extrajudiciales que estime pertinentes.<br>
                    El Usuario será exclusiva e ilimitadamente responsable por los perjuicios que su conducta pueda causar a <strong>ManagCond</strong> o a los restantes Usuarios de la <strong>Plataforma </strong>y el<strong> Sitio</strong>.</li>
                <li><strong>Declaración del Usuario Pagador</strong>. El <strong>Usuario Pagador</strong>, en el acto de pagar el dinero a recaudar, establece su conformidad con el producto adquirido y o servicio recibido, cuya transacción anterior dio origen a la recaudación a través de la <strong>Plataforma</strong>.</li>
                <li><strong>ManagCond no es entidad financiera</strong>. Se deja expresamente aclarado que <strong>ManagCond</strong> no es una entidad financiera ni presta al Usuario ningún servicio bancario o cambiario, sólo brinda un servicio de pago o recaudación por orden de los Usuarios Mandantes según las condiciones establecidas en los Términos y Condiciones del servicio que da cuenta este instrumento.</li>
                <li><strong>Tarifa por Servicio de Recaudación</strong>. El <strong>Usuario Pagador</strong> acepta pagar una comisión por el servicio de recaudación según el listado de Tarifas vigentes que es expuesto en el <strong>Sitio</strong> facultando a <strong>ManagCond</strong> en forma expresa para que deduzca al momento de la recaudación los dineros equivalentes al servicio acordado de cada transacción comercial por concepto de pago de los servicios de recaudación.</li>
                <li><strong>Seguridad y Confidencialidad de datos personales</strong>. El <strong>Usuario</strong> declara conocer y aceptar la política de confidencialidad y se obliga a guardar absoluta reserva sobre los datos aquí proporcionados. Toda la información personal proporcionada por el <strong>Usuario</strong>, incluidos los datos de información bancaria, es de responsabilidad exclusiva de quien la aporta. La información ingresada por el <strong>Usuario</strong> será utilizada por <strong>ManagCond</strong> para registrarlo en los programas y servicios, darle seguimiento a los servicios, contestar correos electrónicos y proporcionar información con respecto a sus movimientos y respecto de los bienes y servicios contratados. <strong>ManagCond</strong> se reserva el derecho de usar esta información para enviar al <strong>Usuario</strong> correos electrónicos o comunicarse telefónicamente él con información relativa a sus operaciones en el <strong>Sitio</strong> o la <strong>Plataforma</strong>. El <strong>Usuario</strong> siempre podrá solicitar el cese de envío de los correos electrónicos. <strong>ManagCond</strong> no venderá, ni alquilará a otras empresas la información personal de los Usuarios, tampoco la cederá en ningún contexto. La información de los Usuarios es propiedad de quién la aporta y del Usuario que es indiviadualizado con esta, cumpliendo fines relativos a los servicios contratados en COMUNIDAD&nbsp;FELIZ. Estos datos serán utilizados para prestar el Servicio que da cuenta este instrumento. Toda la información personal transmitida se hace a través de una página de Internet segura que protege y encripta la información sensible. La información personal se almacena en servidores o medios magnéticos que mantienen altos estándares de seguridad. La <strong>Plataforma</strong> siempre almacena los datos sensibles de los <strong>Usuarios</strong> en forma encriptada. La <strong>Plataforma</strong> en términos de seguridad transaccional, utiliza la infraestructura que proveen los Operadores de Medios de Pago que son proveedores de la <strong>Plataforma</strong> <strong>ManagCond</strong> y no es responsable por la pérdida o el daño eventual que puedan sufrir los archivos enviados al <strong>Usuario</strong> ya sea por problemas técnicos, hecho suyos o de sus dependientes, razón por la que es responsabilidad del <strong>Usuario</strong> el respaldo de la información que se le envía.<br>
                    <strong>ManagCond</strong> hará sus mejores esfuerzos para mantener la confidencialidad y seguridad de que trata esta sección, pero no responderá por perjuicios que se puedan derivar de la violación de dichas medidas por parte de terceros que utilicen las redes públicas o el Internet para acceder a dicha información.</li>
                <li><strong>Modificaciones de los Términos y Condiciones del Servicio de Pago o Recaudación</strong>. <strong>ManagCond</strong> podrá modificar en cualquier momento los Términos y Condiciones del Servicio de Recaudación. <strong>ManagCond</strong> notificará los cambios al <strong>Usuario</strong> publicando una versión actualizada de dichos Términos y Condiciones en la <strong>Plataforma</strong> con expresión de la fecha de la última modificación y enviará un correo electrónico a la dirección del <strong>Usuario</strong> registrada en la <strong>Plataforma.</strong> Los Términos y Condiciones del Servicio de recaudación modificados serán aplicables a toda Orden de pago o recaudación que se celebre con posterioridad a la notificación al <strong>Usuario</strong>.</li>
                <li><strong>Incorporación de nuevos medios de pago</strong>. <strong>ManagCond</strong> podrá agregar nuevos medios de pago al registro del <strong>Usuario Mandante</strong>, siempre que los medios de pago sean: (a) adicionales a los existentes en la <strong>Plataforma</strong> a la fecha de la agregación y (b) la tarifa del nuevo medio de pago sea menor o esté en el rango de las tarifas previamente registradas por el <strong>Usuario Mandante</strong> en la <strong>Plataforma</strong>.</li>
                <li><strong>Modificación del prestador de servicios</strong>. El servicio ManagCond podrá ser prestado por otra persona jurídica, siempre que la nueva entidad prestadora pertenezca al mismo grupo empresarial de acuerdo al artículo 96 de la ley de Mercado de Valores y no signifique un cambio en la naturaleza del servicio prestado. De producirse esta modificación la continuadora se sujetará de manera inmediata a las cláusulas de estos Términos y Condiciones.</li>
                <li><strong>Terminación del Contrato</strong>. <strong>ManagCond</strong> y el Usuario del Servicio podrán en cualquier oportunidad de vigencia del presente contrato terminarlo sin expresión de causa alguna, lo que implicará la eliminación del Registro del <strong>Usuario</strong>. A los efectos de ejercer esta facultad, es necesario que la parte que pretende la terminación del contrato no adeude a la otra ni a terceros involucrados en las operaciones el cumplimiento de alguna obligación.<br>
                    Asimismo, <strong>ManagCond</strong> podrá, en caso de incumplimiento del Usuario a las condiciones del presente contrato o a la legislación aplicable en la materia, dar por terminada la prestación del Servicio sin ningún tipo de aviso previo, reservándose el derecho de reclamar los daños y perjuicios que tal incumplimiento le haya causado.</li>
                <li><strong>Interrupción del servicio de la Plataforma</strong>. Se deja constancia que la <strong>Plataforma</strong> podría interrumpirse temporalmente entre múltiples causas, por fenómenos de la naturaleza, hechos de terceros, por razones de caso fortuito o fuerza mayor tales como sismos, cortes de energía eléctrica y o servicio telefónico y o líneas de transmisión de datos, intervenciones de redes por parte de terceros, no funcionamiento de redes públicas y o privadas, actos vandálicos o terroristas, huelgas u otros similares u otras causas no imputables a ManagCond, así como, por necesidad urgente de ManagCond de realizar tareas de soporte, <strong>mantención y/o aseguramiento</strong> de la futura continuidad operacional de la Plataforma.</li>
                <li><strong>Documentación</strong>. El <strong>Usuario</strong> podrá hacer copias de la presente documentación. El <strong>Usuario</strong> autoriza en forma irrevocable a <strong>ManagCond</strong> y/o a quien <strong>ManagCond</strong> designe, a grabar las operaciones del <strong>Usuario</strong> relativas los servicios prestados por y <strong>Sitio</strong> y la <strong>Plataforma</strong>, y a utilizar dichas grabaciones como medio probatorio ante autoridades administrativas y/o judiciales. Las constancias emitidas por <strong>ManagCond</strong> serán consideradas prueba suficiente del cumplimiento de las instrucciones: órdenes de pago o recaudación, notificaciones de pago o recaudación, correos electrónicos, conversaciones telefónicas, registros computacionales e informes sustituyen la necesidad de cualquier recibo y son plenamente oponibles al <strong>Usuario</strong>. A tales efectos, el <strong>Usuario</strong> y <strong>ManagCond</strong> acuerdan otorgarle valor probatorio a las constancias que se emitan como consecuencia de las aprobaciones o instrucciones dadas por el <strong>Usuario</strong>, con el alcance establecido en la legislación vigente.</li>
                <li><strong>Notificaciones</strong>. Serán válidas todas las notificaciones realizadas a los <strong>Usuarios</strong> por la <strong>Plataforma</strong> y <strong>ManagCond</strong> en la dirección de correo electrónico principal registrada por éstos.</li>
                <li><strong>Domicilios</strong>. Se fija como domicilio de <strong>ManagCond</strong> en la calle Avenida Libertador Bernardo O’Higgins 949 piso 21, Santiago, Chile. El domicilio constituido por los Usuarios a los fines de los Servicios de Recaudación es el domicilio registrado por los Usuarios en la <strong>Plataforma</strong>.</li>
                <li><strong>Anexos</strong>. Forma parte integral e inseparable de los Términos y Condiciones de Uso incorporados en este acuerdo, el Listado de Tarifas Vigentes que pueden ser vistas en el <strong>Sitio</strong>.</li>
                <li><strong>Controversias</strong> Cualquier dificultad o controversia que se produzca entre los contratantes respecto de la aplicación, interpretación, duración, validez o ejecución de este contrato o cualquier otro motivo, será sometida a arbitraje conforme al Reglamento Procesal de arbitrajes del Centro de Arbitraje y Mediación de Santiago, vigente al momento de solicitarlo. Las partes confieren poder especial irrevocable a la Cámara de Comercio de Santiago A.G., para que, a petición escrita de cualquiera de ellas, designe a un árbitro arbitrador en cuanto al procedimiento y de derecho en cuanto al fallo, de entre los integrantes del cuerpo arbitral del Centro de Arbitraje y Mediación de Santiago.&nbsp; En contra de las resoluciones del árbitro no procederá recurso alguno. El árbitro queda especialmente facultado para resolver todo asunto relacionado con su competencia y/o jurisdicción.</li>
            </ol>
            <p>Las tarifas vigentes de cada <strong>Usuario Mandante</strong> se encuentran detalladas en www.managcond.cl/tarifas_pago_online.</p>
            <p><strong>ManagCond</strong> se reserva el derecho de modificar las tarifas de todos sus productos y servicios en caso de que las condiciones de mercado varíen.<br>
            </p>
            <p>
                <br>
            </p>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="assets/bower_components/jquery/dist/jquery.min.js"><\/script>')</script>

</body>
</html>

